application: battleship-1376
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:       # static then dynamic

- url: /static
  static_dir: static
- url: /
  static_files: static/index.html
  upload: static/index\.html
  secure: always

- url: /_ah/spi/.*
  script: seawars_api.api
  secure: always

- url: /tasks/send_confirmation_email
  script: main.app

- url: /tasks/send_reminder_email
  script: main.app

libraries:

- name: endpoints
  version: latest
